# Generated by Django 2.2.1 on 2019-06-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(choices=[('anatomy', 'Anatomy'), ('physiology', 'Physiology'), ('biochemistry', 'Biochemistry'), ('general medicine', 'General Medicine'), ('general surgerys', 'General Surgery'), ('orthopaedics', 'Orthopaedics'), ('paediatrics', 'Paediatrics'), ('obstetrics & gynaecology', 'Obstetrics & Gynaecology'), ('ophthalmology', 'Ophthalmology'), ('otorhinolaryngology(ENT)', 'Otorhinolaryngology(ENT)'), ('dermatology', 'Dermatology'), ('anaesthesiology', 'Anaesthesiology'), ('psychiatry', 'Psychiatry'), ('radio diagnosis & imaging', 'Radio diagnosis & Imaging'), ('community medicine', 'Community Medicine'), ('pulmonary medicine', 'Pulmonary Medicine'), ('urology', 'Urology'), ('nephrology', 'Nephrology'), ('neuroscience', 'Neuroscience'), ('gastroenterology', 'Gastroenterology'), ('cardiology', 'Cardiology'), ('ctvs', 'CTVS'), ('endocrinology', 'Endocrinology'), ('oncology', 'Oncology')], max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('eqpid', models.CharField(max_length=200)),
                ('eqpname', models.CharField(max_length=200)),
                ('fromDate', models.DateField()),
                ('toDate', models.DateField()),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
