# Generated by Django 2.2.1 on 2019-06-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentrequests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentrequest',
            name='user_id',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
