# Generated by Django 2.2.2 on 2019-06-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentrequests', '0002_equipmentrequest_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentrequest',
            name='request_status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='equipmentrequest',
            name='department',
            field=models.CharField(choices=[('anatomy', 'Anatomy'), ('physiology', 'Physiology'), ('biochemistry', 'Biochemistry'), ('general medicine', 'General Medicine'), ('general surgerys', 'General Surgery'), ('orthopaedics', 'Orthopaedics'), ('paediatrics', 'Paediatrics'), ('obstetrics & gynaecology', 'Obstetrics & Gynaecology'), ('ophthalmology', 'Ophthalmology'), ('otorhinolaryngology', 'Otorhinolaryngology'), ('dermatology', 'Dermatology'), ('anaesthesiology', 'Anaesthesiology'), ('psychiatry', 'Psychiatry'), ('radio diagnosis & imaging', 'Radio diagnosis & Imaging'), ('community medicine', 'Community Medicine'), ('pulmonary medicine', 'Pulmonary Medicine'), ('urology', 'Urology'), ('nephrology', 'Nephrology'), ('neuroscience', 'Neuroscience'), ('gastroenterology', 'Gastroenterology'), ('cardiology', 'Cardiology'), ('ctvs', 'CTVS'), ('endocrinology', 'Endocrinology'), ('oncology', 'Oncology')], max_length=200),
        ),
    ]
