# Generated by Django 2.2.2 on 2019-06-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentrequests', '0003_auto_20190618_0546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentrequest',
            name='eqpid',
        ),
    ]
