# Generated by Django 2.2.1 on 2019-05-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('Equipment_ID', models.CharField(max_length=200)),
                ('Equipment_Name', models.CharField(max_length=200)),
                ('Incharge_ID', models.CharField(max_length=200)),
                ('Department', models.CharField(choices=[('anatomy', 'Anatomy'), ('physiology', 'Physiology'), ('biochemistry', 'Biochemistry'), ('general medicine', 'General Medicine'), ('general surgerys', 'General Surgery'), ('orthopaedics', 'Orthopaedics'), ('paediatrics', 'Paediatrics'), ('obstetrics & gynaecology', 'Obstetrics & Gynaecology'), ('ophthalmology', 'Ophthalmology'), ('otorhinolaryngology(ENT)', 'Otorhinolaryngology(ENT)'), ('dermatology', 'Dermatology'), ('anaesthesiology', 'Anaesthesiology'), ('psychiatry', 'Psychiatry'), ('radio diagnosis & imaging', 'Radio diagnosis & Imaging'), ('community medicine', 'Community Medicine'), ('pulmonary medicine', 'Pulmonary Medicine'), ('urology', 'Urology'), ('nephrology', 'Nephrology'), ('neuroscience', 'Neuroscience'), ('gastroenterology', 'Gastroenterology'), ('cardiology', 'Cardiology'), ('ctvs', 'CTVS'), ('endocrinology', 'Endocrinology'), ('oncology', 'Oncology')], max_length=200)),
                ('Institution', models.CharField(choices=[('ks hegde medical academy', 'KS HEGDE MEDICAL ACADEMY'), ('nmam insitute of technology', 'NMAM INSTITUTE OF TECHNOLOGY'), ('nitte institue of communication', 'NITTE INSTITUTE OF COMMUNICATION')], default='ks hegde medical academy', max_length=200)),
                ('Status', models.CharField(default='available', max_length=200)),
                ('Product_ID', models.CharField(max_length=200)),
                ('Company', models.CharField(max_length=200)),
                ('Utilities', models.TextField(blank=True)),
                ('Consumables', models.TextField(blank=True)),
                ('image_main', models.ImageField(upload_to='photos/%Y%m%d/')),
            ],
        ),
    ]
