# Generated by Django 2.2.1 on 2019-06-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='Status',
            field=models.CharField(choices=[('available', 'AVAILABLE'), ('not available', 'NOT AVAILABLE'), ('under maintenance', 'UNDER MAINTENANCE')], default='available', max_length=200),
        ),
    ]
