# Generated by Django 2.2.1 on 2019-06-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_auto_20190612_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='Equipment_ID',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
