# Generated by Django 2.2.1 on 2019-06-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_auto_20190613_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='Equipment_Name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
