# Generated by Django 2.2.1 on 2020-03-28 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_auto_20190613_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='auto_increment_id',
            new_name='id',
        ),
    ]
