# Generated by Django 2.2.1 on 2020-03-29 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0005_auto_20200329_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='Equipment_ID',
        ),
    ]
